### ISSUE TITLE
Migrate to PostgresSQL 

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/GroupManager#1]
### Descriptive summary

Update the app to use PostgresSQL instead of Oracle.

**Comment by jgorney** [comment]
Hi Everyone,

Can Ron and I perform the final migration from Oracle to Postgres on this?  Thank you!

**Comment by VivianChu** [comment]
@jgorney - Some functions in GroupManager in test environment are not working correctly.  I'm working on them now.  I'll let you know when I'm done.  Thanks

**Comment by jgorney** [comment]
OK.  Ron and I moved the postgres database from abbott to wwhite - did that cause a problem???

**Comment by VivianChu** [comment]
@jgorney - No, the problem is that the object could not be saved.  rg.postgresql.util.PSQLException: ERROR: relation "dual" does not exist   I'm trying to update the app and the sql statement to fix it.

**Comment by jgorney** [comment]
Oh right - "dual" is Oracle-specific.
